ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_by INTEGER REFERENCES users(id);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS updated_by INTEGER REFERENCES users(id);
ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id);
ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE community_groups ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE community_events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE community_events ADD COLUMN IF NOT EXISTS updated_by INTEGER REFERENCES users(id);
ALTER TABLE community_events ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id);
ALTER TABLE community_events ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE community_events ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE community_events ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE resources ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE resources ADD COLUMN IF NOT EXISTS updated_by INTEGER REFERENCES users(id);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_by INTEGER REFERENCES users(id);
ALTER TABLE services ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id);
ALTER TABLE services ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE services ADD COLUMN IF NOT EXISTS media_url VARCHAR(500);
ALTER TABLE services ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;